language: none
script:
  - npm test
branches:
  only:
    - gh-pages
notifications:
  on_success: change
  on_failure: change
after_success:
  - openssl aes-256-cbc -K $encrypted_6f1f023cd8f1_key -iv $encrypted_6f1f023cd8f1_iv -in travis_key.enc -out travis_key -d
  - mv travis_key ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com"                >> ~/.ssh/config
  - echo -e "\n\tStrictHostKeyChecking no"   >> ~/.ssh/config
  - git config --global user.email "sairoutine@gmail.com"
  - git config --global user.name "sairoutine"
  - git clone --branch=gh-pages git@github.com:sairoutine/Koishibow.git
  - cd $TRAVIS_BUILD_DIR/Koishibow/
  - ls
  - ls -al
  - npm install -g gulp
  - npm install
  - git submodule update --init --recursive
  - cd $TRAVIS_BUILD_DIR/Koishibow/src/
  - cd $TRAVIS_BUILD_DIR/Koishibow/src/js/
  - cd $TRAVIS_BUILD_DIR/Koishibow/src/js/hakureijs/
  - git checkout master
  - npm install
  - cd $TRAVIS_BUILD_DIR/Koishibow/
  - gulp build
  - git status
  - git add ./public/
  - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - ssh -T git@github.com
  - git push origin gh-pages

