name: Compile js and push it

on:
  push:
    branches:
      - 'gh-pages'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '7'
    - name: Build JS
      run: |
        npm install
        git config --global user.email "sairoutine@gmail.com"
        git config --global user.name "sairoutine"
        git submodule update --init --recursive
        cd ./src/js/hakureijs/
        npm install
        cd ../../../
        npm run build:js
        git add ./public/
        git commit -m "compile js by Github Action" || echo
        git push origin gh-pages
        sleep 10
    - name: Test
      run: npm test

